services:
  - redis-server
language: node_js
node_js:
  - '0.10' # Version of nodejs in the Ubuntu repository
  - 'node' # Latest stable version
  - '6'    # Latest "current" version
before-script:
  - node node_modules/.bin/eslint src/
script:
  - node node_modules/.bin/babel src/ -d dist/